### ISSUE TITLE
Whitelabel Error Page for /builds during test execution. Some tests missing after.

### ISSUE THREAD

**Issue by csiegler** [anshooarora/klov#36]
Hi there, I am using Klov with the CucumberExtentReports plugin, and during execution of my tests, the /builds page returns me a Whitelabel Error page status 500 with the below error.

I am using MongoDB 3.2, Klov 0.0.3, and am attaching my KlovReporter to an ExtentReports created by the CucumberExtentReporter plugin. (https://github.com/email2vimalraj/CucumberExtentReporter)

Also, the entire first Feature run during execution is missing from the report/build even though on the /dashboard I can see the steps for that Feature in the "Activity" column.

Here is the log with the error:

`ERROR 25280 --- [p-nio-80-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IndexOutOfBoundsException: Index: 0, Size: 0] with root cause`

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[na:1.8.0_161]
        at java.util.ArrayList.get(Unknown Source) ~[na:1.8.0_161]
        at com.aventstack.klov.controllers.ReportViewController.builds(ReportViewController.java:66) ~[classes!/:0.0.3]
        at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_161]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_161]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_161]
`

**Comment by csiegler** [comment]
Here is what I mean with the missing feature. On the /builds page I can see the report says for 2 features (intended) but when I click on that report I only see one.

![klovbug](https://user-images.githubusercontent.com/20520181/37780969-d1c6a56a-2dbd-11e8-9bda-f6a171e2817b.png)
![only-one-feature-klov](https://user-images.githubusercontent.com/20520181/37780974-d2a30af0-2dbd-11e8-8942-21f34c28fc72.png)

**Comment by anshooarora** [comment]
ExtentReports version?

**Comment by csiegler** [comment]
ExtentReports 3.1.3

I've done some more digging and I think the problem lies in the way I am using the CucumberExtentReporter plugin. 

Because native Klov support hasn't been released yet with the plugin, I am attaching the KlovReporter during a @before(order = 0) hook. 

The com.cucumber.listener.ExtentCucumberFormatter (from the plugin) executes before any of the step file constructors or @before hooks are called. So it is creating the ExtentReports object and the first Feature/Scenario before there is any KlovReporter attached. This is causing those com.aventstack.extentreports.model.Test to not be stored in the mongoDB (they have no mongoid). 

I confirmed that this was happening by looking into the mongoDB for my Klov server. There are tests with null parents, though the parentName will show in the collection. (Ex. "parent" : null, "parentName" : "Scenario 1") When I query for a test by that name (or by manually checking all the collections) there is no such test, indicating that those tests were never stored in the mongoDB.

The solution I believe is either to modify the ExtentCucumberFormatter within the external library to attach a KlovReporter at the same time it attaches its ExtentHtmlReporter, or to wait until the next release of CucumberExtentReporter plugin, which will have native klov support according to this issue: https://github.com/email2vimalraj/CucumberExtentReporter/issues/67

**Comment by anshooarora** [comment]
There was someone having this exact issue.  Make sure Klov instance is not created multiple times.

**Comment by csiegler** [comment]
Yeah I made sure the Klov instance is only created once. I will try to use a workaround with a "dummy feature" run before my real features. Is there a timeline on when the native support release of CucumberExtentReporter plugin will be published?

**Comment by anshooarora** [comment]
I am not sure as Vimal maintains that repo.  I can tell you that there will be several fixes released in Klov with version 0.1 very soon, some are for the BDD report.

**Comment by buekera** [comment]
I'm facing the same issue. I also made sure I only have one klov instance. I achieved that by using a singleton with the groovy `@Singleton` annotation.

**Comment by anshooarora** [comment]
Version of ExtentReports? Klov? MongoDb?

At present, recommended versions are:

ExtentReports 3.1.3
Klov 0.1.0
MongoDb 3.2

PS.  You shouldn't see a white label page if you are using Klov 0.1.0.

**Comment by buekera** [comment]
Versions:

ExtentReports 3.1.3
Klov 0.1.0
MongoDb 3.4.10

I'm not getting the "white label page" anymore since I updated to klov 0.1.0 but I still get the same exception as posted by @csiegler and the fallback page you are describing:

Error log: https://gist.github.com/buekera/83149431b200627acf44be1311585c43
Screenshot:
![image](https://user-images.githubusercontent.com/12516018/38075163-ae4b4694-3331-11e8-8f38-62658303040c.png)

**Comment by anshooarora** [comment]
Please use MongoDb 3.2 and check if the error is still present.  If it is, please share a sample of the tests to help me reproduce.

**Comment by buekera** [comment]
I tried downgrading to MongoDb 3.2 but get the same results:

Here are some snippets of my code:

This block initiates the reporter, but only once.
```
def first = true

Before() {
    if (first) {
        Reporter.loadXMLConfig(new File('src/test/resources/extent-config.xml'))
        Reporter.extentReport.setGherkinDialect('de')

        KlovInstance.instance.klovInstance = new KlovReporter('Report', 'Default')
        KlovInstance.instance.klovInstance.setKlovUrl('http://localhost:9191')
        KlovInstance.instance.klovInstance.initMongoDbConnection('localhost', 27017)
        Reporter.getExtentReport().attachReporter(KlovInstance.instance.klovInstance)

        first = false
    }
}
```

Sample of a test (step definition) wirtten in Groovy:
```
Given(~/^I'm on the login page$/) { ->
    at LoginPage
}

When(~/^I enter my credentials with username ([^"]*) and password ([^"]*)$/) { String username, String password ->
    page.login(username, password)
}

Then(~/^I'm successfully logged in$/) { ->
    assert page instanceof LoginPage
}
```

Do you need anything else?
